### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by TheVikingWarrior** [Adaptivity/LocalizationsForMCFMods#14]
Hey @Adaptivity, do you mind if I store some translations here?

**Comment by Adaptivity** [comment]
Yes, of course! I gave you push-access. Feel free to credit you in README.md and adding translations for mods which are not in the repository.

**Comment by TheVikingWarrior** [comment]
ok, cool, thanks :+1:

**Comment by fewizz** [comment]
:+1:
