### ISSUE TITLE
Chromaticraft & Rotarycraft

### ISSUE THREAD

**Issue by Mazdallier** [Adaptivity/LocalizationsForMCFMods#31]
These two mod are in github BUT they use XML file format in lang sub-folder.

**Comment by Adaptivity** [comment]
They are probably not support resource packs. Try to contact with Reika and add your .xml files into the mod itself.

**Comment by 3TUSK** [comment]
You probably want to translate those xml files and [make a new folder named like `fr_FR`](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/52#issuecomment-110082377) and submit it manually like [this one](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/211). @Mazdallier

**Comment by Mazdallier** [comment]
this is done
